app:
  name: "Market Data Platform"
  version: "1.0.0"
  
  directories:
    project_root: "."
    config_dir: "./config"
    data_dir: "./data"
    output_dir: "./data/output"
    universes_dir: "./config/universes"
    sharepoint_dir: "/Users/msyeom/Library/CloudStorage/OneDrive-SharedLibraries-OPTIMALVEST.AIPTE.LTD/Arki Investment - Trading"
    project_sharepoint_dir: "/Users/msyeom/Library/CloudStorage/OneDrive-SharedLibraries-OPTIMALVEST.AIPTE.LTD/Arki Investment - Trading/simple-order-management-platform"
    # Local storage mode (safer for testing)
    local_root: "/Users/msyeom/arki"
    local_output_dir: "/Users/msyeom/arki/portfolio-reports"
    local_market_data_dir: "/Users/msyeom/arki/market-data"
    local_backup_dir: "/Users/msyeom/arki/backups"
  
  logging:
    level: "INFO"
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
  # Email configuration for notifications
  email:
    sender: "minsu.yeom@arkifinance.com"
    recipient: "minsu.yeom@arkifinance.com"
    smtp_server: "smtp.office365.com"
    smtp_port: 587
    use_tls: true
    password: null  # Set email password here or use EMAIL_PASSWORD env var
  
  # Storage mode configuration
  storage:
    mode: "local"  # Options: "sharepoint" or "local"
    # sharepoint: Use SharePoint/OneDrive for production
    # local: Use local directories for testing/development
  
  # Scheduling configuration (Singapore timezone)
  scheduling:
    timezone: "Asia/Singapore"
    market_data_update: "06:00"  # Daily at 6:00 AM SGT
    portfolio_update: "06:30"    # Daily at 6:30 AM SGT
  
  # IBKR Connection Profiles
  ibkr_profiles:
    portfolio_manager:
      description: "Portfolio Manager - Full trading access"
      host: "127.0.0.1"
      port: 4001  # IB Gateway Live account (primary)
      client_id: 1
      timeout: 30
      alternative_ports: [4002, 7497, 7496]  # Try these ports if connection fails (Paper, TWS ports)
      permissions:
        - "portfolio_download"
        - "order_generation"
        - "account_summary"
    
    trade_assistant:
      description: "Trade Assistant - Market data access only"
      host: "127.0.0.1"
      port: 4001  # IB Gateway Live account (primary)
      client_id: 2
      timeout: 30
      alternative_ports: [4002, 7497, 7496]  # Try these ports if connection fails (Paper, TWS ports)
      permissions:
        - "market_data"
        - "universe_update"
        - "price_download"
    
    paper_trader:
      description: "Paper Trading Account"
      host: "127.0.0.1"
      port: 4002  # IB Gateway Paper account
      client_id: 3
      timeout: 30
      alternative_ports: [4001, 7497, 7496]
      permissions:
        - "portfolio_download"
        - "market_data"
    
    alternative_live:
      description: "Alternative Live Account"
      host: "127.0.0.1"
      port: 7497  # TWS Live account
      client_id: 4
      timeout: 30
      alternative_ports: [4001, 4002, 7496]
      permissions:
        - "portfolio_download"
        - "market_data"
  
  # Legacy IB settings (for backward compatibility)
  ib:
    host: "127.0.0.1"
    port: 4001  # IB Gateway Live account (primary)
    client_id: 1
    timeout: 30
    # Alternative ports to try if connection fails
    alternative_ports: [4002, 7497, 7496]  # Paper account, then TWS ports
